name: Josh Lee

headline: >-
  Headline goes here. Example: Data Science degree from Harvard with 3 years of experience in software development.
  Passionate about artificial intelligence and more.

contact:
  -
    icon: 'bi bi-globe'
    name: example.com
    url: 'https://www.example.com'  # replace with your own address
  -
    icon: 'bi bi-envelope'
    name: name@gmail.com
    url: 'mailto:username@gmail.com'  # replace with your own email
  -
    icon: 'bi bi-linkedin'
    name: Josh Lee
    url: 'https://www.linkedin.com/in/username'  # replace with your own address
  -
    icon: 'bi bi-github'
    name: joshtech
    url: 'https://github.com/username'  # replace with your own address
  -
    icon: 'bi bi-youtube'
    name: joshchannel
    url: 'https://youtube.com'  # replace with your own address

language:
  - English
  - Italian
  - Swedish
  - Japanese

programming:
  -
    icon: python.png
    name: Python
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: pytorch.png
    name: PyTorch
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: pyspark.png
    name: PySpark
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: fastapi.png
    name: FastAPI
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: js.png
    name: JavaScript
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: svelte.png
    name: Svelte
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: react.png
    name: React
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: nextjs.svg
    name: Next.js
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: vite.png
    name: Vite
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: swift.png
    name: Swift
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: cpp.png
    name: C++
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: sql.png
    name: sql
    link: 'https://github.com/'  # replace with your own repo address
  -
    icon: git.png
    name: git
    link: 'https://github.com/'  # replace with your own repo address

hobby:
  - Swimming
  - Hiking
  - Cooking

########### Education
education:
  -
    icon: harvard.png
    school: Harvard University
    degree: MSc. in Data Science
    loc: Boston, MA
    time: 2018 ~ 2020 &middot; 2 yrs
    description: >-
      GPA: 4.0/4.0
      <br>
      Thesis: Your Thesis Title Here
      <br>
      Other information here.
  -
    icon: cmu.png
    school: Carnegie Mellon University
    degree: BSc. in Computer Science
    loc: Pittsburgh, PA
    time: 2014 ~ 2018 &middot; 4 yrs
    description: >-
      GPA: 4.0/4.0
      <br>
      Other information here.

########### Experience (optional)
experience:
  -
    icon: google.png
    company: Google
    role: Machine Learning Engineer
    loc: Mountain View, CA
    time: 2022 ~ now
    description: >-
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi condimentum elit justo, vel tristique erat ornare in. Cras ultricies feugiat vehicula. Aenean nulla ipsum, sagittis ac felis vitae, facilisis maximus justo. Nunc ipsum ex, molestie vel velit eu, aliquet posuere velit. In dignissim volutpat ante, non lacinia eros egestas non. Mauris hendrerit orci sit amet metus facilisis, nec sollicitudin justo consectetur. Aenean aliquet velit egestas elementum efficitur. Cras sit amet fringilla arcu.
  -
    icon: amazon.png
    company: Amazon
    role: Software Developer
    loc: Seattle, WA
    time: 2020 ~ 2022 &middot; 2yrs
    description: >-
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi condimentum elit justo, vel tristique erat ornare in. Cras ultricies feugiat vehicula. Aenean nulla ipsum, sagittis ac felis vitae, facilisis maximus justo. Nunc ipsum ex, molestie vel velit eu, aliquet posuere velit. In dignissim volutpat ante, non lacinia eros egestas non. Mauris hendrerit orci sit amet metus facilisis, nec sollicitudin justo consectetur. Aenean aliquet velit egestas elementum efficitur. Cras sit amet fringilla arcu.

########### Publications (optional)
publication:
  -
    title: An Awesome Paper with an Awesome Title 2
    author: Josh Lee
    journal: International Conference on Machine Learning (ICML)
    year: 2022
    link: 'http://arxiv.org/'
  -
    title: An Awesome Paper with an Awesome Title 1
    author: Josh Lee
    journal: International Conference on Learning Representations (ICLR)
    year: 2021
    link: 'http://arxiv.org/'

########### Projects (optional)
project:
  -
    icon: github.svg
    name: awesome-project-one
    link: 'https://github.com/'
    description: |
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi condimentum elit justo, vel tristique erat ornare in. Aenean aliquet velit egestas elementum efficitur. Cras sit amet fringilla arcu.
  -
    icon: github.svg
    name: awesome-project-two
    link: 'https://github.com/'
    description: |
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi condimentum elit justo, vel tristique erat ornare in. Aenean aliquet velit egestas elementum efficitur. Cras sit amet fringilla arcu.